### ISSUE TITLE
Can't build: java.lang.IllegalStateException: bundle org.eclipse.equinox.p2.repository is not started

### ISSUE THREAD

**Issue by garydgregory** [vogellacompany/codemodify#16]
Using git commit (the latest as of now):
```
commit 4a477e0d7d7ed23b221f810014f4adb64237e967 (HEAD -> master, origin/master, origin/HEAD)
```
Running:
```
mvn -V clean verify -X
```
I get:
```
...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] releng 1.0.0-SNAPSHOT .............................. SUCCESS [  0.075 s]
[INFO] [bundle] Codemodify 0.1.0-SNAPSHOT ................. FAILURE [  0.825 s]
[INFO] [feature] Code Modifier Feature 1.3.0 .............. SKIPPED
[INFO] [updatesite] de.simonscholz.codemodify.build.p2.eclipse-repository 1.0.0-SNAPSHOT SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.364 s
[INFO] Finished at: 2024-08-31T13:11:40-04:00
[INFO] ------------------------------------------------------------------------
[DEBUG] [87e4f93e-c53e-475c-a444-8b93db7b5dbd][extension>org.eclipse.tycho:tycho-maven-plugin:4.0.2] Searching bundle for class interface org.eclipse.equinox.p2.core.IProvisioningAgent and location file:/Users/garydgregory/.m2/repository/org/eclipse/platform/org.eclipse.equinox.p2.core/2.9.200/org.eclipse.equinox.p2.core-2.9.200.jar
[DEBUG] [87e4f93e-c53e-475c-a444-8b93db7b5dbd][extension>org.eclipse.tycho:tycho-maven-plugin:4.0.2] Return bundle org.eclipse.equinox.p2.core for location file:/Users/garydgregory/.m2/repository/org/eclipse/platform/org.eclipse.equinox.p2.core/2.9.200/org.eclipse.equinox.p2.core-2.9.200.jar
[ERROR] bundle org.eclipse.equinox.p2.repository is not started
java.lang.IllegalStateException: bundle org.eclipse.equinox.p2.repository is not started
    at org.eclipse.equinox.internal.p2.repository.Activator.getContext (Activator.java:65)
    at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.restoreFromSystemProperty (AbstractRepositoryManager.java:1013)
    at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.restoreRepositories (AbstractRepositoryManager.java:1033)
    at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.basicGetRepository (AbstractRepositoryManager.java:182)
    at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository (AbstractRepositoryManager.java:666)
    at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository (MetadataRepositoryManager.java:110)
    at org.eclipse.tycho.p2maven.transport.RemoteMetadataRepositoryManager.loadRepository (RemoteMetadataRepositoryManager.java:68)
    at org.eclipse.tycho.p2maven.transport.RemoteMetadataRepositoryManager.loadRepository (RemoteMetadataRepositoryManager.java:59)
    at org.eclipse.tycho.p2.resolver.URITargetDefinitionContent.loadMetadataRepositories (URITargetDefinitionContent.java:113)
    at org.eclipse.tycho.p2.resolver.URITargetDefinitionContent.preload (URITargetDefinitionContent.java:77)
    at org.eclipse.tycho.p2.resolver.URITargetDefinitionContent.query (URITargetDefinitionContent.java:62)
    at org.eclipse.equinox.p2.query.CompoundQueryable.getIteratorFromQueryable (CompoundQueryable.java:178)
    at org.eclipse.equinox.p2.query.CompoundQueryable.everything (CompoundQueryable.java:124)
    at org.eclipse.equinox.internal.p2.metadata.expression.RepeatableIterator$IndexProviderIterator.<init> (RepeatableIterator.java:142)
    at org.eclipse.equinox.internal.p2.metadata.expression.RepeatableIterator.create (RepeatableIterator.java:60)
    at org.eclipse.equinox.internal.p2.metadata.expression.Everything.<init> (Everything.java:39)
    at org.eclipse.equinox.internal.p2.metadata.expression.ContextExpression.createContext (ContextExpression.java:48)
    at org.eclipse.equinox.p2.query.ExpressionQuery.perform (ExpressionQuery.java:51)
    at org.eclipse.equinox.internal.p2.metadata.index.IndexProvider.query (IndexProvider.java:26)
    at org.eclipse.equinox.internal.p2.metadata.index.IndexProvider.query (IndexProvider.java:36)
    at org.eclipse.tycho.p2resolver.InstallableUnitResolver.findUnit (InstallableUnitResolver.java:281)
    at org.eclipse.tycho.p2resolver.InstallableUnitResolver.findUnits (InstallableUnitResolver.java:261)
    at org.eclipse.tycho.p2resolver.InstallableUnitResolver.getRootIUs (InstallableUnitResolver.java:254)
    at org.eclipse.tycho.p2resolver.InstallableUnitResolver.addLocation (InstallableUnitResolver.java:88)
    at org.eclipse.tycho.p2resolver.TargetDefinitionResolver.resolveContentWithExceptions (TargetDefinitionResolver.java:149)
    at org.eclipse.tycho.p2resolver.TargetDefinitionResolver.resolveContent (TargetDefinitionResolver.java:106)
    at org.eclipse.tycho.p2resolver.TargetDefinitionResolverService.resolveFromArguments (TargetDefinitionResolverService.java:96)
    at java.util.concurrent.ConcurrentHashMap.computeIfAbsent (ConcurrentHashMap.java:1708)
    at org.eclipse.tycho.p2resolver.TargetDefinitionResolverService.getTargetDefinitionContent (TargetDefinitionResolverService.java:70)
    at org.eclipse.tycho.p2resolver.TargetPlatformFactoryImpl.resolveTargetDefinitions (TargetPlatformFactoryImpl.java:323)
    at org.eclipse.tycho.p2resolver.TargetPlatformFactoryImpl.createTargetPlatform (TargetPlatformFactoryImpl.java:212)
    at org.eclipse.tycho.p2resolver.TargetPlatformFactoryImpl.createTargetPlatform (TargetPlatformFactoryImpl.java:178)
    at org.eclipse.tycho.p2resolver.TargetPlatformFactoryImpl.createTargetPlatform (TargetPlatformFactoryImpl.java:116)
    at org.eclipse.tycho.p2resolver.ReactorRepositoryManagerImpl.computePreliminaryTargetPlatform (ReactorRepositoryManagerImpl.java:71)
    at org.eclipse.tycho.p2resolver.P2DependencyResolver.computePreliminaryTargetPlatform (P2DependencyResolver.java:215)
    at org.eclipse.tycho.core.resolver.DefaultTychoResolver.resolveProject (DefaultTychoResolver.java:101)
    at org.eclipse.tycho.core.maven.TychoProjectExecutionListener.beforeProjectLifecycleExecution (TychoProjectExecutionListener.java:108)
    at org.apache.maven.lifecycle.internal.CompoundProjectExecutionListener.beforeProjectLifecycleExecution (CompoundProjectExecutionListener.java:42)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:103)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:906)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:283)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:206)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke (Method.java:580)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:255)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:201)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:361)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:314)
[ERROR]
[DEBUG] Shutting down adapter factory; available factories [file-lock, rwlock-local, semaphore-local, noop]; available name mappers [discriminating, file-gav, file-hgav, file-static, gav, static]
...
```
Using the provided `mvnw` script is no better:
```
./mvnw  clean verify -X
Downloading https://repo1.maven.org/maven2/org/apache/maven/apache-maven/3.3.9/apache-maven-3.3.9-bin.zip
..............................................................................................................................................................................................................................................................................................................................................................................................................................................
Unzipping /Users/garydgregory/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2/apache-maven-3.3.9-bin.zip to /Users/garydgregory/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2
Set executable permissions for: /Users/garydgregory/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2/apache-maven-3.3.9/bin/mvn
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T11:41:47-05:00)
Maven home: /Users/garydgregory/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2/apache-maven-3.3.9
Java version: 21.0.4, vendor: Homebrew
Java home: /usr/local/Cellar/openjdk@21/21.0.4/libexec/openjdk.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "14.6.1", arch: "x86_64", family: "mac"
[DEBUG] Reading global settings from /Users/garydgregory/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2/apache-maven-3.3.9/conf/settings.xml
[DEBUG] Reading user settings from /Users/garydgregory/.m2/settings.xml
[DEBUG] Using manager EnhancedLocalRepositoryManager with priority 10.0 for /Users/garydgregory/.m2/repository
[ERROR] Error executing Maven.
java.lang.ArrayIndexOutOfBoundsException: Index 11169 out of bounds for length 8192
	at org.codehaus.plexus.util.xml.pull.MXParser.parsePI(MXParser.java:2502)
	at org.codehaus.plexus.util.xml.pull.MXParser.nextImpl(MXParser.java:1283)
	at org.codehaus.plexus.util.xml.pull.MXParser.next(MXParser.java:1131)
	at org.apache.maven.model.io.xpp3.MavenXpp3Reader.nextTag(MavenXpp3Reader.java:566)
	at org.apache.maven.model.io.xpp3.MavenXpp3Reader.parsePluginExecution(MavenXpp3Reader.java:2926)
	at org.apache.maven.model.io.xpp3.MavenXpp3Reader.parsePlugin(MavenXpp3Reader.java:2739)
	at org.apache.maven.model.io.xpp3.MavenXpp3Reader.parsePluginManagement(MavenXpp3Reader.java:3007)
	at org.apache.maven.model.io.xpp3.MavenXpp3Reader.parseBuild(MavenXpp3Reader.java:978)
	at org.apache.maven.model.io.xpp3.MavenXpp3Reader.parseModel(MavenXpp3Reader.java:2277)
	at org.apache.maven.model.io.xpp3.MavenXpp3Reader.read(MavenXpp3Reader.java:3845)
	at org.apache.maven.model.io.xpp3.MavenXpp3Reader.read(MavenXpp3Reader.java:595)
	at org.apache.maven.model.io.DefaultModelReader.read(DefaultModelReader.java:117)
	at org.apache.maven.model.io.DefaultModelReader.read(DefaultModelReader.java:86)
	at org.apache.maven.model.building.DefaultModelProcessor.read(DefaultModelProcessor.java:81)
	at org.apache.maven.model.building.DefaultModelBuilder.readModel(DefaultModelBuilder.java:533)
	at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally(DefaultModelBuilder.java:1045)
	at org.apache.maven.model.building.DefaultModelBuilder.readParent(DefaultModelBuilder.java:800)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:329)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:320)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:198)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:202)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.collectDependencies(DefaultRepositorySystem.java:316)
	at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveInternal(DefaultPluginDependenciesResolver.java:202)
	at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveCoreExtension(DefaultPluginDependenciesResolver.java:141)
	at org.apache.maven.cli.internal.BootstrapCoreExtensionManager.resolveExtension(BootstrapCoreExtensionManager.java:135)
	at org.apache.maven.cli.internal.BootstrapCoreExtensionManager.resolveCoreExtensions(BootstrapCoreExtensionManager.java:99)
	at org.apache.maven.cli.internal.BootstrapCoreExtensionManager.loadCoreExtensions(BootstrapCoreExtensionManager.java:84)
	at org.apache.maven.cli.MavenCli.loadCoreExtensions(MavenCli.java:662)
	at org.apache.maven.cli.MavenCli.container(MavenCli.java:526)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:281)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.apache.maven.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:39)
	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:122)
	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:50)
```

**Comment by vogella** [comment]
Looks like your Maven version is too old, use Maven 3.9.5. I just update the Tycho version and build works fine for me.
